#%RAML 1.0 NamedExample
value:
  - name: HDFC Bank Offer
    description: Use HDFC Credit card to get 20% discount  
  - name : Kotak Bank Offer
    description: Use Kotak Credit card to get 20% discount
  - name : Coupon code
    description: Use OFFER30 to get 20% discount    