#%RAML 1.0 NamedExample
value: 
  -
    ID: 1 
    pincode: 560029
    pricePerDay: 3500
    hotelName: Oyo 1123 Mayura Nandan
    address: 1-3/32, 3rd street, Anand Nagar
    city: Bangalore
    emptyRooms: 10
    room: 
      type: Standard
      bedSize: King
      temperatureControl: true
  -
    ID: 2
    pincode: 560033
    pricePerDay: 2500
    hotelName: Oyo 1124 Sundar Sadan
    address: 2-3/22, 3rd street, Vasanth Nagar
    city: Bangalore
    emptyRooms: 10
    room: 
      type: Standard
      bedSize: King
      temperatureControl: true